server:
  port: 38081

spring:
    datasource:
        platform: h2
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:_test_mem
        username: mem
        password: mem123
    jpa:
        properties:
            eclipselink.persistence-context.flush-mode: COMMIT
            eclipselink.weaving: static
            eclipselink.ddl-generation: drop-and-create-tables
            eclipselink.logging.timestamp: false
            eclipselink.logging.session: false
            eclipselink.logging.connection: false
            eclipselink.logging.thread: false
            eclipselink.logging.level.transaction: ALL
            eclipselink.logging.level.sql: FINE
            eclipselink.logging.level.event: ALL
            eclipselink.logging.level.connection: ALL
            eclipselink.logging.level.query: FINE
            eclipselink.logging.level.cache: ALL
            eclipselink.logging.level: ALL
            eclipselink.logging.parameters: true
            eclipselink.cache.shared.default: false